name = "beat-sheets"
main = "src/index.js"
compatibility_date = "2024-01-15"

[env.production]
route = "beat-sheets.mobicycle-productions.workers.dev/*"

[env.development]
compatibility_date = "2024-01-15"

[[env.production.d1_databases]]
binding = "SCREENPLAY_DRAFT"
database_name = "screenplay-draft"
database_id = "your-d1-database-id"

[[env.production.kv_namespaces]]
binding = "ALLY_BEAT_SHEETS"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-id"

[env.production.vars]
API_KEY = "your-api-key"
CF_ZONE_ID = "your-zone-id"