name = "beat-sheets"
main = "src/index.js"
compatibility_date = "2024-01-15"
account_id = "bdf4cedbc60ca9b2c1374c11996a67d7"

# [env.production]
# route = "beat-sheets.mobicycle-productions.workers.dev/*"

[env.development]
compatibility_date = "2024-01-15"

# D1 database for screenplay data
# [[env.production.d1_databases]]
# binding = "SCREENPLAY_DRAFT"
# database_name = "screenplay-draft"
# database_id = "your-d1-database-id"

# KV namespace for future sync functionality
# [[env.production.kv_namespaces]]
# binding = "ALLY_BEAT_SHEETS"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-id"

# Environment variables for production
# [env.production.vars]
# API_KEY = "your-api-key"
# CF_ZONE_ID = "your-zone-id"